# Generated by Django 2.0.1 on 2018-03-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0004_auto_20180302_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
