# Generated by Django 2.0.1 on 2018-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0006_auto_20180320_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_movies',
            field=models.ManyToManyField(related_name='recommended_movies', to='mea.Movie'),
        ),
    ]
