# Generated by Django 2.0.1 on 2018-02-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LandingPageUser',
        ),
    ]
